nameReference:
  - kind: SecretStore
    group: external-secrets.io
    fieldSpecs:
      - kind: ExternalSecret
        group: external-secrets.io
        path: spec/secretStoreRef/name
  - kind: ServiceAccount
    fieldSpecs:
      - kind: SecretStore
        group: external-secrets.io
        path: spec/provider/kubernetes/auth/serviceAccount/name
