apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: community-marketplace

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-store.yaml
  - external-secrets.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - web-deployment.yaml
  - meilisearch-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - postgres-backup-cronjob.yaml

configurations:
  - eso-nameref.yaml

images:
  - name: community-marketplace/api
    newTag: unpinned
  - name: community-marketplace/worker
    newTag: unpinned
  - name: community-marketplace/web
    newTag: unpinned

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: community-marketplace
