import { API_NAMESPACES } from './rbac-routes';

export const WEB_API_ROUTES = {
  buyer: {
    favorites: `${API_NAMESPACES.BUYER}/favorites`,
    payments: `${API_NAMESPACES.BUYER}/payments`,
    paymentsIntent: `${API_NAMESPACES.BUYER}/payments/intent`,
    paymentsConfirm: `${API_NAMESPACES.BUYER}/payments/confirm`,
    paymentsRefunds: `${API_NAMESPACES.BUYER}/payments/refunds`,
    wallet: '/buyer/wallet',
    notifications: `${API_NAMESPACES.BUYER}/notifications`,
    notificationPreferences: `${API_NAMESPACES.BUYER}/notifications/preferences`,
    notificationsRead: `${API_NAMESPACES.BUYER}/notifications/read`,
    notificationsReadAll: `${API_NAMESPACES.BUYER}/notifications/read-all`,
    reviews: `${API_NAMESPACES.BUYER}/reviews`,
    reviewsPending: `${API_NAMESPACES.BUYER}/reviews/pending`,
    notificationsUnreadCount: `${API_NAMESPACES.BUYER}/notifications/unread-count`,
    trustMe: `${API_NAMESPACES.BUYER}/trust/me`,
    trustProfile: (buyerId: string) => `${API_NAMESPACES.BUYER}/trust/${buyerId}`,
    profile: `${API_NAMESPACES.BUYER}/profile`,
    reports: `${API_NAMESPACES.BUYER}/reports`,
    listingReport: (listingId: string) => `${API_NAMESPACES.BUYER}/listings/${listingId}/report`,
    chat: `${API_NAMESPACES.BUYER}/chat`,
  },
  seller: {
    listings: `${API_NAMESPACES.SELLER}/listings`,
    listingsAnalyticsSummary: `${API_NAMESPACES.SELLER}/listings/analytics/summary`,
    listingImages: (id: string) => `${API_NAMESPACES.SELLER}/listings/${id}/images`,
    earnings: `${API_NAMESPACES.SELLER}/earnings`,
    earningsPayouts: `${API_NAMESPACES.SELLER}/earnings/payouts`,
    connectOnboard: `${API_NAMESPACES.SELLER}/earnings/connect/onboard`,
    connectStatus: `${API_NAMESPACES.SELLER}/earnings/connect/status`,
    platformFee: `${API_NAMESPACES.SELLER}/earnings/platform-fee`,
    boostCatalog: `${API_NAMESPACES.SELLER}/monetization/boosts/catalog`,
    boostIntent: `${API_NAMESPACES.SELLER}/monetization/boosts/intent`,
    boostConfirm: `${API_NAMESPACES.SELLER}/monetization/boosts/confirm`,
    notifications: `${API_NAMESPACES.SELLER}/notifications`,
    notificationPreferences: `${API_NAMESPACES.SELLER}/notifications/preferences`,
    notificationsRead: `${API_NAMESPACES.SELLER}/notifications/read`,
    notificationsReadAll: `${API_NAMESPACES.SELLER}/notifications/read-all`,
    notificationsUnreadCount: `${API_NAMESPACES.SELLER}/notifications/unread-count`,
    profile: `${API_NAMESPACES.SELLER}/profile`,
    verification: `${API_NAMESPACES.SELLER}/verification`,
    statusHistory: `${API_NAMESPACES.SELLER}/status-history`,
    reviews: `${API_NAMESPACES.SELLER}/reviews`,
    reviewsPending: `${API_NAMESPACES.SELLER}/reviews/pending`,
    chat: `${API_NAMESPACES.SELLER}/chat`,
  },
  chat: {
    inbox: '/chat/inbox',
    threads: '/chat/threads',
    messages: '/chat/messages',
    markRead: '/chat/messages/read',
  },
  messages: {
    send: '/messages/send',
    list: '/messages/list',
    conversation: (id: string) => `/messages/conversation/${id}`,
    report: '/messages/report',
    block: '/messages/block',
  },
  disputes: {
    create: '/disputes/create',
    uploadEvidence: '/disputes/upload-evidence',
    respond: '/disputes/respond',
    mine: '/disputes/mine',
    detail: (id: string) => `/disputes/${id}`,
  },
  public: {
    listings: '/listings',
    listingSearch: '/listings/search',
    search: '/search',
    autocomplete: '/search/autocomplete',
    globalSearch: '/search/global',
    auth: {
      login: '/auth/login',
      register: '/auth/register',
      registerComplete: '/auth/register/complete',
      refresh: '/auth/refresh',
      logout: '/auth/logout',
      otpSend: '/auth/otp/send',
      otpVerify: '/auth/otp/verify',
      activate: '/auth/activate',
      activateResend: '/auth/activate/resend',
    },
  },
  users: {
    me: '/users/me',
    mePermissions: '/users/me/permissions',
    meSettings: '/users/me/settings',
  },
} as const;
