import { API_NAMESPACES } from './rbac-routes';

export const WEB_API_ROUTES = {
  buyer: {
    favorites: `${API_NAMESPACES.BUYER}/favorites`,
    payments: `${API_NAMESPACES.BUYER}/payments`,
    paymentsIntent: `${API_NAMESPACES.BUYER}/payments/intent`,
    paymentsConfirm: `${API_NAMESPACES.BUYER}/payments/confirm`,
    paymentsRefunds: `${API_NAMESPACES.BUYER}/payments/refunds`,
    statementsStatus: `${API_NAMESPACES.BUYER}/statements/status`,
    statementsIntent: `${API_NAMESPACES.BUYER}/statements/intent`,
    statementsConfirm: `${API_NAMESPACES.BUYER}/statements/confirm`,
    statementsDownload: `${API_NAMESPACES.BUYER}/statements/download`,
    checkoutCreateSession: '/checkout/create-session',
    orderRefund: '/order/refund',
    wallet: '/buyer/wallet',
    notifications: `${API_NAMESPACES.BUYER}/notifications`,
    notificationPreferences: `${API_NAMESPACES.BUYER}/notifications/preferences`,
    notificationsRead: `${API_NAMESPACES.BUYER}/notifications/read`,
    notificationsReadAll: `${API_NAMESPACES.BUYER}/notifications/read-all`,
    reviews: `${API_NAMESPACES.BUYER}/reviews`,
    reviewsPending: `${API_NAMESPACES.BUYER}/reviews/pending`,
    notificationsUnreadCount: `${API_NAMESPACES.BUYER}/notifications/unread-count`,
    trustMe: `${API_NAMESPACES.BUYER}/trust/me`,
    trustProfile: (buyerId: string) => `${API_NAMESPACES.BUYER}/trust/${buyerId}`,
    profile: `${API_NAMESPACES.BUYER}/profile`,
    reports: `${API_NAMESPACES.BUYER}/reports`,
    listingReport: (listingId: string) => `${API_NAMESPACES.BUYER}/listings/${listingId}/report`,
    chat: `${API_NAMESPACES.BUYER}/chat`,
  },
  seller: {
    listings: `${API_NAMESPACES.SELLER}/listings`,
    listingsAnalyticsSummary: `${API_NAMESPACES.SELLER}/listings/analytics/summary`,
    listingImages: (id: string) => `${API_NAMESPACES.SELLER}/listings/${id}/images`,
    earnings: `${API_NAMESPACES.SELLER}/earnings`,
    earningsPayouts: `${API_NAMESPACES.SELLER}/earnings/payouts`,
    connectOnboard: `${API_NAMESPACES.SELLER}/earnings/connect/onboard`,
    connectOnboardAlias: '/seller/onboard',
    connectStatus: `${API_NAMESPACES.SELLER}/earnings/connect/status`,
    connectDashboard: `${API_NAMESPACES.SELLER}/earnings/connect/dashboard`,
    earningsPayments: `${API_NAMESPACES.SELLER}/earnings/payments`,
    earningsPurchases: `${API_NAMESPACES.SELLER}/earnings/purchases`,
    earningsStatement: `${API_NAMESPACES.SELLER}/earnings/statement`,
    earningsPendingTransfers: `${API_NAMESPACES.SELLER}/earnings/transfers/pending`,
    settleOrder: '/seller/settle-order',
    platformFee: `${API_NAMESPACES.SELLER}/earnings/platform-fee`,
    boostCatalog: `${API_NAMESPACES.SELLER}/monetization/boosts/catalog`,
    boostIntent: `${API_NAMESPACES.SELLER}/monetization/boosts/intent`,
    boostConfirm: `${API_NAMESPACES.SELLER}/monetization/boosts/confirm`,
    featuredCatalog: `${API_NAMESPACES.SELLER}/monetization/featured/catalog`,
    featuredIntent: `${API_NAMESPACES.SELLER}/monetization/featured/intent`,
    featuredConfirm: `${API_NAMESPACES.SELLER}/monetization/featured/confirm`,
    fastTrackStatus: `${API_NAMESPACES.SELLER}/monetization/fast-track/status`,
    fastTrackIntent: `${API_NAMESPACES.SELLER}/monetization/fast-track/intent`,
    fastTrackConfirm: `${API_NAMESPACES.SELLER}/monetization/fast-track/confirm`,
    storeSlotCatalog: `${API_NAMESPACES.SELLER}/monetization/store-slots/catalog`,
    storeSlotIntent: `${API_NAMESPACES.SELLER}/monetization/store-slots/intent`,
    storeSlotConfirm: `${API_NAMESPACES.SELLER}/monetization/store-slots/confirm`,
    notifications: `${API_NAMESPACES.SELLER}/notifications`,
    notificationPreferences: `${API_NAMESPACES.SELLER}/notifications/preferences`,
    notificationsRead: `${API_NAMESPACES.SELLER}/notifications/read`,
    notificationsReadAll: `${API_NAMESPACES.SELLER}/notifications/read-all`,
    notificationsUnreadCount: `${API_NAMESPACES.SELLER}/notifications/unread-count`,
    profile: `${API_NAMESPACES.SELLER}/profile`,
    stores: `${API_NAMESPACES.SELLER}/stores`,
    store: (storeId: string) => `${API_NAMESPACES.SELLER}/stores/${storeId}`,
    storesPrimary: `${API_NAMESPACES.SELLER}/stores/primary`,
    verification: `${API_NAMESPACES.SELLER}/verification`,
    statusHistory: `${API_NAMESPACES.SELLER}/status-history`,
    reviews: `${API_NAMESPACES.SELLER}/reviews`,
    reviewsPending: `${API_NAMESPACES.SELLER}/reviews/pending`,
    chat: `${API_NAMESPACES.SELLER}/chat`,
  },
  admin: {
    notificationsInbox: `${API_NAMESPACES.ADMIN}/notifications/inbox`,
    notificationsInboxUnreadCount: `${API_NAMESPACES.ADMIN}/notifications/inbox/unread-count`,
    notificationsInboxRead: `${API_NAMESPACES.ADMIN}/notifications/inbox/read`,
    notificationsInboxReadAll: `${API_NAMESPACES.ADMIN}/notifications/inbox/read-all`,
  },
  chat: {
    inbox: '/chat/inbox',
    threads: '/chat/threads',
    messages: '/chat/messages',
    markRead: '/chat/messages/read',
  },
  messages: {
    send: '/messages/send',
    list: '/messages/list',
    conversation: (id: string) => `/messages/conversation/${id}`,
    report: '/messages/report',
    block: '/messages/block',
  },
  disputes: {
    create: '/disputes/create',
    uploadEvidence: '/disputes/upload-evidence',
    respond: '/disputes/respond',
    mine: '/disputes/mine',
    detail: (id: string) => `/disputes/${id}`,
  },
  public: {
    listings: '/listings',
    featuredListings: '/listings/featured',
    listingSearch: '/listings/search',
    adsPlacements: '/ads/placements',
    search: '/search',
    autocomplete: '/search/autocomplete',
    globalSearch: '/search/global',
    auth: {
      login: '/auth/login',
      register: '/auth/register',
      registerComplete: '/auth/register/complete',
      refresh: '/auth/refresh',
      logout: '/auth/logout',
      otpSend: '/auth/otp/send',
      otpVerify: '/auth/otp/verify',
      activate: '/auth/activate',
      activatePreview: '/auth/activate/preview',
      activateResend: '/auth/activate/resend',
      adminInvitePreview: '/auth/admin-invite/preview',
      adminInviteAccept: '/auth/admin-invite/accept',
    },
  },
  users: {
    me: '/users/me',
    mePermissions: '/users/me/permissions',
    meSettings: '/users/me/settings',
    meAvatarUploadUrl: '/users/me/avatar/upload-url',
    meAvatar: '/users/me/avatar',
    meStoreBannerUploadUrl: '/users/me/store-banner/upload-url',
    meStoreBanner: '/users/me/store-banner',
    mePhoneSendOtp: '/users/me/phone/send-otp',
    mePhoneVerify: '/users/me/phone/verify',
  },
} as const;
